version: '3.8'
services:
  backend-unit:
    container_name: 'backend-test-unit'
    build:
      context: 'backend'
      dockerfile: 'Dockerfile.dev'
      target: 'unit-test'
    volumes:
      - './backend:/app/backend'
      # - '/app/backend/node_modules/'
      - './.git:/app/.git'
    tty: true
    stdin_open: false

  client-unit:
    container_name: 'client-test-unit'
    build:
      context: 'client'
      dockerfile: 'Dockerfile.dev'
      target: 'unit-test'
    volumes:
      - './client:/app/client'
      - './.git:/app/.git'
    tty: true
    stdin_open: false
