version: '3.8'
services:
  backend:
    container_name: 'backend'
    build:
      context: 'backend'
      dockerfile: 'Dockerfile.dev'
      target: 'dev'
    environment:
      BACKEND_COOKIE_SECRET: ${BACKEND_COOKIE_SECRET}
    volumes:
      - './backend:/app/backend'
      - '/app/backend/node_modules/'
    ports:
      - 4000:4000
    tty: true
    stdin_open: false
