FROM node:15-alpine3.12 as dev

WORKDIR /app/backend

# To use packages in CLI without global install
ENV PATH /app/backend/node_modules/.bin:$PATH

COPY package*.json yarn.lock ./

RUN yarn install --silent

COPY . .

EXPOSE 4000

CMD ["yarn", "dev"]

##########################################################
FROM dev as unit-test

ENV GIT_WORK_TREE=/app/ GIT_DIR=/app/.git

RUN apk update && \
    apk add git

CMD ["yarn", "test"]
